# Generated by Django 5.0.6 on 2024-07-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/rental_images/')),
                ('is_main', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Non-Smoking Rooms', 'Non-Smoking Rooms'), ('Spa and Wellness Center', 'Spa and Wellness Center'), ('Fitness Center', 'Fitness Center'), ('Accessible Facilities', 'Accessible Facilities'), ('Room Service', 'Room Service'), ('Free Wi-Fi', 'Free Wi-Fi'), ('Parking', 'Parking'), ('Air Conditioning', 'Air Conditioning'), ('Coffee/Tea Maker', 'Coffee/Tea Maker'), ('Bar', 'Bar'), ('Family Rooms', 'Family Rooms'), ('Terrace', 'Terrace'), ('Elevator', 'Elevator'), ('Garden', 'Garden'), ('Heating', 'Heating'), ('Swimming Pool', 'Swimming Pool'), ('Pet Friendly', 'Pet Friendly')], max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=40, null=True)),
                ('city', models.CharField(max_length=40)),
                ('country', models.CharField(max_length=40)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rooms', models.IntegerField()),
                ('property_type', models.CharField(choices=[('Apartment', 'Apartment'), ('House', 'House'), ('Hotel', 'Hotel'), ('Studio', 'Studio'), ('Villa', 'Villa'), ('Cabin', 'Cabin'), ('Cottage', 'Cottage')], max_length=50)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('availability_start_date', models.DateField(blank=True, null=True)),
                ('availability_end_date', models.DateField(blank=True, null=True)),
                ('views_count', models.IntegerField(default=0)),
                ('contact_info', models.CharField(blank=True, max_length=255, null=True)),
                ('ratings_sum', models.IntegerField(default=0)),
                ('ratings_count', models.IntegerField(default=0)),
                ('reviews_count', models.IntegerField(default=0)),
                ('verified', models.BooleanField(default=False)),
                ('rejected', models.BooleanField(default=False)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('additional_images', models.ManyToManyField(related_name='rentals', to='rentals.image')),
            ],
        ),
    ]
