# Generated by Django 5.0.6 on 2024-07-11 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Non-Smoking Rooms', 'Non-Smoking Rooms'), ('Spa and Wellness Center', 'Spa and Wellness Center'), ('Fitness Center', 'Fitness Center'), ('Accessible Facilities', 'Accessible Facilities'), ('Room Service', 'Room Service'), ('Free Wi-Fi', 'Free Wi-Fi'), ('Parking', 'Parking'), ('Air Conditioning', 'Air Conditioning'), ('Coffee/Tea Maker', 'Coffee/Tea Maker'), ('Bar', 'Bar'), ('Family Rooms', 'Family Rooms'), ('Terrace', 'Terrace'), ('Elevator', 'Elevator'), ('Garden', 'Garden'), ('Heating', 'Heating'), ('Swimming Pool', 'Swimming Pool'), ('Pet Friendly', 'Pet Friendly')], max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='rental',
            name='tags',
        ),
        migrations.AddField(
            model_name='rental',
            name='tags',
            field=models.ManyToManyField(related_name='rentals', to='rentals.tag'),
        ),
    ]
