# Generated by Django 5.0.6 on 2024-07-13 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0005_image_is_main'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='main_image',
        ),
    ]
