# Generated by Django 5.0.6 on 2024-07-14 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0006_remove_rental_main_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='location',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='ratings_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rental',
            name='ratings_sum',
            field=models.IntegerField(default=0),
        ),
    ]
