# Generated by Django 5.0.6 on 2024-07-15 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0007_rental_location_rental_ratings_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='reviews_count',
            field=models.IntegerField(default=0),
        ),
    ]
