# Generated by Django 5.0.6 on 2024-07-18 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0008_rental_reviews_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
