# Generated by Django 5.0.6 on 2024-07-15 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_and_filters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchhistory',
            name='search_query',
            field=models.CharField(max_length=255),
        ),
    ]
