# Generated by Django 5.0.6 on 2024-07-18 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_and_filters', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchhistory',
            name='asdfasfd',
        ),
    ]
