# Generated by Django 5.0.6 on 2024-07-10 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_landlord',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_moderator',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('User', 'User'), ('Landlord', 'Landlord'), ('Moderator', 'Moderator'), ('Booking Manager', 'Booking Manager'), ('Editor', 'Editor')], default='User', max_length=30),
        ),
    ]
