# Generated by Django 5.0.6 on 2024-07-18 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='rental',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.rental'),
        ),
    ]
